- hosts: localhost
  become: true
  vars_prompt:
    - name: package
      prompt: "Quel paquet voulez-vous installer ?"
      private: no

    - name: version
      prompt: "Quelle version du paquet ?"
      default: latest
      private: no

  tasks:
  - name: install chosen package 
    apt:
      package: "{{ package }}"
      state: "{{ version }}"
